export const COUNTDOWN_TRACK_MESSAGE = '5 4 3 2 1';
export const COUNTDOWN_TRACK_START_SECONDS = 5;
export const COUNTDOWN_TRACK_LEAD_MS = 220;
export const COUNTDOWN_TRACK_DURATION_MS = COUNTDOWN_TRACK_START_SECONDS * 1000;
export const COUNTDOWN_TRACK_PLAYBACK_MS = COUNTDOWN_TRACK_DURATION_MS + COUNTDOWN_TRACK_LEAD_MS;
